### ISSUE TITLE
failed to allocate ... bytes on 0x70000000 😭 

### ISSUE THREAD

**Issue by uwuLegacy** [PlutoSolutions/NullCore#1]
tried various injectors

**Comment by mr-nv** [comment]
inject as soon as you start the game. other than that there is nothing i can tell you, maybe restart your pc and try again

**Comment by mr-nv** [comment]
or i can write a dll that you would need to inject into steam.exe, but youll have 2 dlls that you would need to inject into steam.exe. tell me if i should do that

**Comment by uwuLegacy** [comment]
would be welcome if you don't mind. i'll try what you suggested earlier

**Comment by mr-nv** [comment]
yeah tell me if you have the same issue even when injecting right when the
game starts

пн, 26 дек. 2022 г., 18:49 Legacy ***@***.***>:

**Comment by uwuLegacy** [comment]
hello, figured it out after a restart with the xenos inject on startup option. thanks for the help!

**Comment by mr-nv** [comment]
sounds good man
