### ISSUE TITLE
Crash cfg 

### ISSUE THREAD

**Issue by Autobus41** [PlutoSolutions/NullCore#10]
Can you fix load cfg issue ? Sometimes When u Inject Nullcore Crack  It Works fine But When u Try To Load Cfg it does not load then none of cfg work u need to restard game, or sometimes cfg wont work at all.And can you add skinchanger or something else.

**Comment by mr-nv** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6DycoUf7BrAgQ7jeSnKlr_r4vFJxYKUhgv5JzKz5XXQ&s
