### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by danfanofdead** [PlutoSolutions/NullCore#12]
Failed to allocate (number) bytes  at 0x68F00000 Try restarting your game or use a alternative injector method halp.
how tags very fun

**Comment by danfanofdead** [comment]
I have restarted pc injected multi times in main menu

**Comment by danfanofdead** [comment]
Also alternative version doesn't work either   ):

**Comment by Mimamou1000** [comment]
I too have this problem and sometimes it works by itself so I don't know how to help you because I also have this problem

**Comment by mr-nv** [comment]
restart your pc repeatedly until it works, thats the only way how you can fix it
Not sure if you really need it though...

**Comment by danfanofdead** [comment]
Inject as soon as possible lol
