### ISSUE TITLE
New tf2 update

### ISSUE THREAD

**Issue by ChickenOfDEA** [PlutoSolutions/NullCore#28]
tf2 updated to 64 bit,nullcore also updated to it
can we get an update to the crack?

**Comment by Ethaniscurious** [comment]
you dont need to update it just use the old engine  https://www.youtube.com/watch?v=oLljfQ5kngM&lc=Ugy5465xmFanvJRgUel4AaABAg.A33ahTygsl1A35Ld3TkyVO
