### ISSUE TITLE
projectile aimbot problem

### ISSUE THREAD

**Issue by titaniummachine1** [PlutoSolutions/NullCore#4]
projectile aimbot is not only outdated but hardly ever hits.
can you fix it by adding fedoraware projectile prediction?

**Comment by mr-nv** [comment]
lol no, just use fedoraware or maybe try injecting both nullcore and fedoraware at the same time, maybe itll work

**Comment by titaniummachine1** [comment]
when tutorial how to inject futhere in tlauncher?

śr., 28 gru 2022 o 08:38 mr-nv ***@***.***> napisał(a):

**Comment by mr-nv** [comment]
never, use tl legacy as a normal person and dont use tlauncher its garbage

сб, 31 дек. 2022 г., 17:37 titanium_machine ***@***.***>:
