### ISSUE TITLE
New TeamFortress 2 Update Issues

### ISSUE THREAD

**Issue by Jagoddaa35** [PlutoSolutions/NullCore#7]
yesterday there was tf2 update and after the update some projectile classes woud start to miss allot 
and some classes woud crash when u use aimbot like sniper
if you cloud fix the issues me and my friend woud be happy

**Comment by NUMBERONEMINECRAFTFAN** [comment]
No

**Comment by Jagoddaa35** [comment]
> No

Yes

**Comment by mr-nv** [comment]
https://github.com/PlutoSolutions/NullCore/releases/tag/1.2
