### ISSUE TITLE
Tf2 new update

### ISSUE THREAD

**Issue by Autobus41** [PlutoSolutions/NullCore#8]
Hello yesterday was new tf2 update and now a few class have bugs. sniper crash when you use aimbot (trigger bot dont work) demoman and soldier on they deafult weapons projectile aimbot dont work (pyro flaregun same). If you can fix it I will be thankfull

**Comment by NUMBERONEMINECRAFTFAN** [comment]
No

**Comment by mr-nv** [comment]
https://github.com/PlutoSolutions/NullCore/releases/tag/1.2
